### ISSUE TITLE
Arrow Of Darkness showing no stats

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/aoedb.net#6]
On this page https://aoedb.net/items/2270/40 it shows the legendary item but does not show what the stats are or the benefits except saying its arrows.

**Comment by Zeentch** [comment]
All of the new Athens legendary items haven't had their stats put on aoedb as of yet, Luciano is working on it.

**Comment by ellepereira** [comment]
This should be fixed now @musictopia - let me know!
