### ISSUE TITLE
Celtic quest bug?

### ISSUE THREAD

**Issue by ezrateh** [ProjectCeleste/aoedb.net#7]
I received the quest for grinding gears which tells me to build the gear hall using the blueprint from my inventory but when i tried to build it, it didn't work and now the blueprint has disappeared. Thank You.

**Comment by Zeentch** [comment]
This issue should be reported on the Celeste bug reports not here, this is for aoedb.net.

Link to Celeste bug report: https://github.com/ProjectCeleste/Celeste_Server/issues
